git:
    remote: "https://github.com/hackgt/registration.git"
    branch: "config-paths"

secrets-source: git-hackgt-registration-secrets

files:
  THEME_FILE: resources/registration-demo-config/normalize.css
  QUESTIONS_FILE: resources/registration-demo-config/questions.json
  FAVICON_FILE_BASE64: resources/registration-demo-config/favicon.ico
