git:
    remote: "https://github.com/hackgt/registration.git"
    branch: "fix-undefined-settings"

secrets-source: git-hackgt-registration-secrets
deployment:
    replicas: 1
    strategy:
        type: recreate
