apps:
  - name: helpq
    git: https://github.com/hackgt/helpq.git
    branch: dev
    run: {}

  - name: check-in
    git: https://github.com/HackGT/Ultimate-Checkin.git

  - name: helm-resource
    git: https://github.com/hackgt/helm-resource.git

  - name: mongo
    helm: mongodb
    version: 0.4.3

  - name: juiced-peacock
    helm: redis
    version: 0.4.2
