git:
  remote: https://github.com/HackGT/application-bot.git
  branch: callibration
image_name: gcr.io/hackgt-cluster/application-bot
secrets:
  - ADMIN_KEY_SECRET
  - BOT_TOKEN
  - VERIFICATION_TOKEN
 
